#!/bin/bash

#	gsub("_NIK_TYPENAME_AUTO_", "NIK_TYPENAME_AUTO");

#	gsub("_NIK_MODULE_", "NIK_MODULE");
#	gsub("_NIK_POLICY_", "NIK_POLICY");
#	gsub("_NIK_PREFIX_", "NIK_PREFIX");

#	gsub("_NIK_INDEX_TYPE_", "NIK_INDEX_TYPE");
#	gsub("_NIK_DEPTH_TYPE_", "NIK_DEPTH_TYPE");
#	gsub("_NIK_PA_TYPE_", "NIK_PA_TYPE");
#	gsub("_NIK_DA_TYPE_", "NIK_DA_TYPE");
#	gsub("_NIK_NA_TYPE_", "NIK_NA_TYPE");
#	gsub("_NIK_NP_TYPE_", "NIK_NP_TYPE");
#	gsub("_NIK_RA_TYPE_", "NIK_RA_TYPE");
#	gsub("_NIK_RL_TYPE_", "NIK_RL_TYPE");

mawk_prog='
{
	gsub("NIK_PREFIX _", "NIK_PREFIX nik_");

	print $0;
}'

ls *.hpp |
while read file
do
	cat "$file" | mawk "$mawk_prog" > tmp && mv tmp "$file"
done

