#!/bin/bash

FROM="$1"
TO="$2"

mawk_prog='
{
	gsub("interpret-'"$FROM"'", "compile-'"$TO"'");
	gsub(toupper("interpret_'"$FROM"'"), toupper("compile_'"$TO"'"));

	print $0;
}'

ls *.hpp |
while read file
do
	new_file="$(echo "$file" | mawk "$mawk_prog")"
	cat "$file" | mawk "$mawk_prog" > "$new_file"
done

rm interpret-"$FROM"-*.hpp

